// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTKv4sh7EEvPki3B93rBqV8mjT-9UgfIo',
    appId: '1:5331781592:web:cb501c537ebad29af394ad',
    messagingSenderId: '5331781592',
    projectId: 'free-fire-locator-c7835',
    authDomain: 'free-fire-locator-c7835.firebaseapp.com',
    databaseURL: 'https://free-fire-locator-c7835-default-rtdb.firebaseio.com',
    storageBucket: 'free-fire-locator-c7835.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcHIB1NfmrUr767He1g1E89RrXYDR1Kcw',
    appId: '1:5331781592:android:548efc2dcb0c27eaf394ad',
    messagingSenderId: '5331781592',
    projectId: 'free-fire-locator-c7835',
    storageBucket: 'free-fire-locator-c7835.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuyKnlJge4As4ZzekSL6pp7YN1VYqY9wE',
    appId: '1:5331781592:ios:a5a71f63a6b88f06f394ad',
    messagingSenderId: '5331781592',
    projectId: 'free-fire-locator-c7835',
    storageBucket: 'free-fire-locator-c7835.appspot.com',
    iosClientId: '5331781592-gi1p44r60e3cd7355kmididn0bh1n2a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeFireLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuyKnlJge4As4ZzekSL6pp7YN1VYqY9wE',
    appId: '1:5331781592:ios:a5a71f63a6b88f06f394ad',
    messagingSenderId: '5331781592',
    projectId: 'free-fire-locator-c7835',
    storageBucket: 'free-fire-locator-c7835.appspot.com',
    iosClientId: '5331781592-gi1p44r60e3cd7355kmididn0bh1n2a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeFireLocation',
  );
}
