// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrbf_vM-znpKkE4ZHu3RWzUP_n4YG6BOI',
    appId: '1:320174623311:web:525e210a97281f4368f83a',
    messagingSenderId: '320174623311',
    projectId: 'free-fire-locator',
    authDomain: 'free-fire-locator.firebaseapp.com',
    storageBucket: 'free-fire-locator.appspot.com',
    measurementId: 'G-16MT0P04ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu3eTEmLxxJ2lf8mbxvD_RnWC3lSMopnI',
    appId: '1:320174623311:android:195ffb870a4ee1aa68f83a',
    messagingSenderId: '320174623311',
    projectId: 'free-fire-locator',
    storageBucket: 'free-fire-locator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALynwGtP0nYcg1ReAp6hE_b9dcO_A-JD8',
    appId: '1:320174623311:ios:80a160f47b10f4d968f83a',
    messagingSenderId: '320174623311',
    projectId: 'free-fire-locator',
    storageBucket: 'free-fire-locator.appspot.com',
    iosClientId: '320174623311-euqdnonbua8bjvgqcju3jdm3a5rn1e9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeFireLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALynwGtP0nYcg1ReAp6hE_b9dcO_A-JD8',
    appId: '1:320174623311:ios:80a160f47b10f4d968f83a',
    messagingSenderId: '320174623311',
    projectId: 'free-fire-locator',
    storageBucket: 'free-fire-locator.appspot.com',
    iosClientId: '320174623311-euqdnonbua8bjvgqcju3jdm3a5rn1e9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeFireLocation',
  );
}
