// Mocks generated by Mockito 5.3.2 from annotations
// in free_fire_location/test/map/features/data/repositories/weather_info_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:free_fire_location/features/map/data/datasources/weather_info_datasource.dart'
    as _i3;
import 'package:free_fire_location/features/map/data/models/weather_model.dart'
    as _i2;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherModel_0 extends _i1.SmartFake implements _i2.WeatherModel {
  _FakeWeatherModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherInfoDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherInfoDatasource extends _i1.Mock
    implements _i3.WeatherInfoDatasource {
  MockWeatherInfoDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherModel> getWeatherByCoordinates(
          {required _i5.LatLng? latLng}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherByCoordinates,
          [],
          {#latLng: latLng},
        ),
        returnValue: _i4.Future<_i2.WeatherModel>.value(_FakeWeatherModel_0(
          this,
          Invocation.method(
            #getWeatherByCoordinates,
            [],
            {#latLng: latLng},
          ),
        )),
      ) as _i4.Future<_i2.WeatherModel>);
}
