// Mocks generated by Mockito 5.3.2 from annotations
// in free_fire_location/test/map/features/domain/usecases/get_fire_info_nasa_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:free_fire_location/core/error/failures.dart' as _i7;
import 'package:free_fire_location/features/map/data/datasources/fire_info_datasource_inpe.dart'
    as _i3;
import 'package:free_fire_location/features/map/data/datasources/fire_info_datasource_nasa.dart'
    as _i2;
import 'package:free_fire_location/features/map/data/repositories/fire_info_repository_impl.dart'
    as _i5;
import 'package:free_fire_location/features/map/domain/entities/fire_page_entity.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFireInfoDatasourceNasa_0 extends _i1.SmartFake
    implements _i2.FireInfoDatasourceNasa {
  _FakeFireInfoDatasourceNasa_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFireInfoDatasourceInpe_1 extends _i1.SmartFake
    implements _i3.FireInfoDatasourceInpe {
  _FakeFireInfoDatasourceInpe_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FireInfoRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockFireInfoRepositoryImpl extends _i1.Mock
    implements _i5.FireInfoRepositoryImpl {
  MockFireInfoRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FireInfoDatasourceNasa get datasourceNasa => (super.noSuchMethod(
        Invocation.getter(#datasourceNasa),
        returnValue: _FakeFireInfoDatasourceNasa_0(
          this,
          Invocation.getter(#datasourceNasa),
        ),
      ) as _i2.FireInfoDatasourceNasa);
  @override
  _i3.FireInfoDatasourceInpe get datasourceInpe => (super.noSuchMethod(
        Invocation.getter(#datasourceInpe),
        returnValue: _FakeFireInfoDatasourceInpe_1(
          this,
          Invocation.getter(#datasourceInpe),
        ),
      ) as _i3.FireInfoDatasourceInpe);
  @override
  _i6.Future<_i4.Either<_i7.Failure, _i8.FirePageEntity>> getFireLocationsInpe(
          {required int? amount}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFireLocationsInpe,
          [],
          {#amount: amount},
        ),
        returnValue:
            _i6.Future<_i4.Either<_i7.Failure, _i8.FirePageEntity>>.value(
                _FakeEither_2<_i7.Failure, _i8.FirePageEntity>(
          this,
          Invocation.method(
            #getFireLocationsInpe,
            [],
            {#amount: amount},
          ),
        )),
      ) as _i6.Future<_i4.Either<_i7.Failure, _i8.FirePageEntity>>);
  @override
  _i6.Future<_i4.Either<_i7.Failure, _i8.FirePageEntity>> getFireLocationsNasa(
          {int? amount = 0}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFireLocationsNasa,
          [],
          {#amount: amount},
        ),
        returnValue:
            _i6.Future<_i4.Either<_i7.Failure, _i8.FirePageEntity>>.value(
                _FakeEither_2<_i7.Failure, _i8.FirePageEntity>(
          this,
          Invocation.method(
            #getFireLocationsNasa,
            [],
            {#amount: amount},
          ),
        )),
      ) as _i6.Future<_i4.Either<_i7.Failure, _i8.FirePageEntity>>);
}
